#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=zirconium
#SBATCH --gres=gpu:1
#SBATCH --job-name=rollout-basic-n50-acc-noise8e-7-nosmooth
#SBATCH --error=output/experimental/log/%x-%j.err
#SBATCH --output=output/experimental/log/%x-%j.out

. "/home/TUE/s131727/miniconda3/etc/profile.d/conda.sh"
conda activate tggnn
python3 \
 -m experimental.remesh.predict_basic \
 -c output/experimental/basic_n50_acc_noise8e-7_nosmooth.pt \
 -n 100 \
 -it 15 \
 --target-acceleration \
 ~/git/bubble-data/n50 \
 output/experimental/rollout/basic-n50-acc-noise8e-7-nosmooth
conda deactivate
