#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=zirconium
#SBATCH --gres=gpu:1
#SBATCH --job-name=rollout-add-n50-it7-k3-vrem-pred-noise5e-6-full
#SBATCH --error=output/experimental/memory/rollout/%x-%j.err
#SBATCH --output=output/experimental/memory/rollout/%x-%j.out

. "/home/TUE/20214195/miniconda3/etc/profile.d/conda.sh"
conda activate tggnn
python3 \
 -m experimental.remesh.predict_memory \
 -c output/experimental/memory/test_new_n50_it7_k3_vrem_noise8e-1 \
 -n 7000 \
 -id 1000 \
 -it 7 \
 --remesh-velocity \
 ~/mirror/bubble-data/ \
 output/experimental/rollout/test_new_n50_it7_k3_vrem_noise8e-1 
conda deactivate
